### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by frostedoyster** [lab-cosmo/mops#20]
From #7, it's clear that we should probably have the same function parameter names in all APIs. Personally, I would go for the single capital letters (`A`, `B`, `P_A`, `C`, `R` and so on), but there might be advantages for other names

**Comment by Luthaf** [comment]
I'm fine with `A`, `B`, `C` for the main tensors, but I would prefer `tensor_a`, `tensor_b`, `tensor_c`. I generally follow a rule that a variable name length should be proportional to it's scope, and one letter function arguments contrtradict this. But I can live with smaller names if needed.

My comment on #7 was more about renaming `P_A` (it is not very clear what `P` means here) with something like `indices_a` or something in this direction; clarifying the relationship between `A` and `P_A`.
